version: '3.8'

services:
  # Backend API Service
  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=development
      - DATABASE_URL=mysql://user:password@mysql:3306/mdhub
      - MONGODB_URL=mongodb://mongodb:27017/mdhub
      - ZMQ_PUBLISHER_PORT=5555
    volumes:
      - ./apps/api:/app
      - /app/__pycache__
    depends_on:
      - mysql
      - mongodb
    networks:
      - mdhub-network
    restart: unless-stopped

  # Frontend Web Dashboard
  web:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - NEXT_PUBLIC_WS_URL=ws://localhost:8000
    volumes:
      - ./apps/web:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - api
    networks:
      - mdhub-network
    restart: unless-stopped

  # MySQL Database
  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=mdhub
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/mysql/init:/docker-entrypoint-initdb.d
    networks:
      - mdhub-network
    restart: unless-stopped

  # MongoDB Database
  mongodb:
    image: mongo:7.0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=mdhub
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./database/mongodb/init:/docker-entrypoint-initdb.d
    networks:
      - mdhub-network
    restart: unless-stopped

  # Redis (for caching and session management)
  redis:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - mdhub-network
    restart: unless-stopped
    command: redis-server --appendonly yes

volumes:
  mysql_data:
  mongodb_data:
  redis_data:

networks:
  mdhub-network:
    driver: bridge